import { Buildings, Clock, Database, EnvelopeSimple, FileText, Gear, IdentificationBadge, ShieldCheck, UsersThree } from "@phosphor-icons/react/dist/ssr";
import { PageHeader, Panel, StatCard, StatusPill } from "./operations-ui";
import styles from "./core-operations.module.css";

export function AdministrationWorkspace() {
  const areas = [[<UsersThree key="u" size={18}/>,"Users & access","Invite users, assign roles, and review privileged access"],[<Buildings key="s" size={18}/>,"School configuration","Manage identity, locale, terms, and inherited values"],[<Gear key="i" size={18}/>,"Integrations","Monitor payment, messaging, identity, and data connections"],[<FileText key="a" size={18}/>,"Audit evidence","Search sensitive actions, exports, approvals, and changes"],[<Database key="j" size={18}/>,"Jobs & data operations","Track imports, exports, synchronization, and retention"],[<ShieldCheck key="p" size={18}/>,"Security controls","Review sessions, MFA coverage, and support access"]] as const;
  return <div className={styles.page}><PageHeader action="Invite user" description="Operate identity, access, integrations, audit evidence, data jobs, and school configuration with clear ownership and control health." eyebrow="Administration / Control center" secondaryAction="View audit log" title="Administration center" />
    <section className={styles.adminHero}><div><h2>Platform controls are operating normally</h2><p>No critical security findings are open. Three invitations, six dormant accounts, and one expiring payment credential need review before the end of this week.</p></div><div className={styles.controlScore}><div><strong>100%</strong><span>Privileged MFA</span></div><div><strong>99.98%</strong><span>30-day availability</span></div><div><strong>0</strong><span>Critical findings</span></div></div></section>
    <section aria-label="Administration statistics" className={styles.stats}><StatCard detail="Across 13 role templates" icon={<UsersThree size={19}/>} label="Active users" value="214"/><StatCard detail="Oldest invitation is 4 days" icon={<EnvelopeSimple size={19}/>} label="Pending invitations" tone="amber" value="3"/><StatCard detail="Payment gateway needs review" icon={<Gear size={19}/>} label="Healthy integrations" tone="violet" value="8 / 9"/><StatCard detail="Past 24 hours" icon={<FileText size={19}/>} label="Audit events" tone="green" value="428"/></section>
    <div className={styles.grid}><div className={styles.stack}><Panel description="Governance and platform operations" title="Administrative workspaces"><div className={styles.adminAreas}>{areas.map(([icon,title,description])=><article className={styles.adminArea} key={title}><div>{icon}</div><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></Panel><Panel action="Search all events" description="Recent sensitive and administrative activity" title="Audit activity"><div className={styles.auditList}>{[["09:42","Role assignment changed","Nusrat Jahan added Finance Approver to Imran Hossain","Recorded","success"],["09:18","Student export generated","Attendance summary · 1,284 records · Principal","Expiring","info"],["08:55","School setting updated","Emergency contact number · Administrator","Recorded","success"],["Yesterday","Support access requested","Vendor case SUP-1842 · awaiting school approval","Approval","warning"]].map(([time,title,detail,status,tone])=><article className={styles.auditItem} key={`${time}-${title}`}><div><strong>{title}</strong><span>{time} · {detail}</span></div><StatusPill tone={tone as "success"|"info"|"warning"}>{status}</StatusPill></article>)}</div></Panel></div>
      <aside className={styles.stack}><Panel action="Manage integrations" description="Production connection status" title="Integration health"><div className={styles.integrationList}>{[["Payment gateway","Healthy · last sync 2 min ago","Healthy","success"],["SMS provider","Healthy · 98.8% delivery","Healthy","success"],["Email delivery","Healthy · no active suppression spike","Healthy","success"],["Accounting export","Credential expires in 12 days","Review","warning"]].map(([name,detail,status,tone])=><article className={styles.integration} key={name}><div><strong>{name}</strong><span>{detail}</span></div><StatusPill tone={tone as "success"|"warning"}>{status}</StatusPill></article>)}</div></Panel><Panel action="Open access review" description="Controls requiring an owner decision" title="Administration queue"><div className={styles.queueList}>{[["Pending user invitations","3 invitations · oldest is 4 days","Review","warning"],["Dormant accounts","6 accounts inactive for 90+ days","Review","warning"],["Privileged access review","Quarterly certification due in 7 days","Due soon","info"]].map(([title,detail,status,tone])=><article className={styles.queueItem} key={title}><div><strong>{title}</strong><span>{detail}</span></div><StatusPill tone={tone as "warning"|"info"}>{status}</StatusPill></article>)}</div></Panel></aside></div>
  </div>;
}

export function SchoolSettingsWorkspace() {
  const nav = [[IdentificationBadge,"School profile"],[Buildings,"Organization & scope"],[Clock,"Locale & time"],[Gear,"Academic defaults"],[EnvelopeSimple,"Communication"],[ShieldCheck,"Safety & compliance"]] as const;
  return <div className={styles.page}><PageHeader action="Save draft" description="Review effective school configuration, understand inherited organization values, and publish controlled changes with clear impact." eyebrow="Administration / School settings" secondaryAction="Change history" title="School settings" />
    <section aria-label="Configuration statistics" className={styles.stats}><StatCard detail="11 fully configured" icon={<Gear size={19}/>} label="Configuration sections" value="12"/><StatCard detail="From organization defaults" icon={<Buildings size={19}/>} label="Inherited values" tone="violet" value="46"/><StatCard detail="2 require approval" icon={<Clock size={19}/>} label="Draft changes" tone="amber" value="4"/><StatCard detail="One recommendation remains" icon={<ShieldCheck size={19}/>} label="Policy compliance" tone="green" value="98%"/></section>
    <div className={styles.settingsShell}><Panel className={styles.settingsNavPanel} title="Settings"><div className={styles.settingsNav}>{nav.map(([Icon,label],index)=><button className={index===0?styles.activeSetting:""} key={label} type="button"><Icon size={16}/>{label}</button>)}</div></Panel>
      <div className={styles.settingsContent}><div className={styles.scopeBanner}><div><strong>Editing Greenfield High School</strong><span>School-level values override organization defaults only where policy allows.</span></div><button type="button">View effective values</button></div><Panel description="Identity shown in staff, family, reports, receipts, and official communication" title="School profile"><div className={styles.formGrid}><div className={`${styles.field} ${styles.full}`}><label htmlFor="school-name">Official school name</label><input defaultValue="Greenfield High School" id="school-name"/><small>Used on official documents and outbound communications.</small></div><div className={styles.field}><label htmlFor="school-code">School code</label><input defaultValue="GFHS-DHK-01" id="school-code"/><small>Stable identifier; changing it requires organization approval.</small></div><div className={styles.field}><label htmlFor="education-board">Education board</label><select defaultValue="dhaka" id="education-board"><option value="dhaka">Dhaka Education Board</option></select><small>Controls report terminology and certificate metadata.</small></div><div className={styles.field}><label htmlFor="timezone">Time zone</label><select defaultValue="dhaka" id="timezone"><option value="dhaka">Asia/Dhaka (UTC+06:00)</option></select><small>Inherited from the organization and locked for this school.</small></div><div className={styles.field}><label htmlFor="language">Primary language</label><select defaultValue="english" id="language"><option value="english">English</option><option value="bangla">Bangla</option></select><small>Individual users may still choose their display language.</small></div><div className={`${styles.field} ${styles.full}`}><label htmlFor="address">Official address</label><input defaultValue="12 Education Road, Dhanmondi, Dhaka 1209" id="address"/><small>Appears on receipts, certificates, and official exports.</small></div></div><footer className={styles.settingsFooter}><span>Last published 18 July 2026 by School Administrator</span><div><button className={styles.secondaryButton} type="button">Discard changes</button><button className={styles.primaryButton} type="button">Review & publish</button></div></footer></Panel>
        <div className={styles.equalGrid}><Panel description="Validation and policy findings" title="Configuration readiness"><div className={styles.settingsList}><article className={styles.settingsItem}><div><strong>Emergency contact</strong><span>A secondary emergency number is required.</span></div><StatusPill tone="danger">Required</StatusPill></article><article className={styles.settingsItem}><div><strong>Academic year transition</strong><span>New defaults take effect on 1 August 2026.</span></div><StatusPill tone="warning">Review</StatusPill></article><article className={styles.settingsItem}><div><strong>School identity</strong><span>All required official fields are complete.</span></div><StatusPill tone="success">Complete</StatusPill></article></div></Panel><Panel description="Changes not yet effective" title="Draft change set"><div className={styles.settingsList}><article className={styles.settingsItem}><div><strong>Primary language</strong><span>English → English and Bangla</span></div><StatusPill tone="info">Draft</StatusPill></article><article className={styles.settingsItem}><div><strong>Receipt footer</strong><span>Updated finance office contact details</span></div><StatusPill tone="warning">Approval</StatusPill></article></div></Panel></div>
      </div></div>
  </div>;
}
