"use client";
import { useState } from "react";
import { Bell, Buildings, CalendarBlank, CheckCircle, Clock, MagnifyingGlass, PencilSimple, SlidersHorizontal, Trash, UsersThree, WarningCircle, X } from "@phosphor-icons/react";
import { PageHeader, Panel, ProgressRow, StatCard, StatusPill, type StatusTone } from "./operations-ui";
import styles from "./core-operations.module.css";
type Tab="Month"|"Week"|"Agenda"|"Academic calendar"|"Room bookings";
const tabs:Tab[]=["Month","Week","Agenda","Academic calendar","Room bookings"];
const days=[29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,1,2];
type CalendarEvent={label:string;kind:"event"|"exam"|"deadline";time:string;location:string;audience:string;description:string};
const initialEvents:Record<number,CalendarEvent>={8:{label:"Staff meeting",kind:"event",time:"2:30 PM",location:"Conference room",audience:"All teaching staff",description:"Monthly coordination meeting and department updates."},14:{label:"Result review",kind:"exam",time:"10:00 AM",location:"Academic office",audience:"Academic leadership",description:"Review and approve the term assessment results."},22:{label:"Fee reminder",kind:"deadline",time:"1:15 PM",location:"Online publication",audience:"214 family accounts",description:"Publish the scheduled reminder for accounts with a balance due."},26:{label:"Assessment 1",kind:"exam",time:"9:00 AM",location:"Academic block",audience:"Grades 6–10",description:"First scheduled assessment day for the current term."},28:{label:"Family meeting",kind:"event",time:"3:00 PM",location:"Assigned classrooms",audience:"Students and guardians",description:"Parent–teacher progress meetings across all grades."},31:{label:"Fee deadline",kind:"deadline",time:"5:00 PM",location:"Finance office",audience:"All active accounts",description:"Final payment deadline for July tuition charges."}};
const week=[
 ["08:00","Sunday","Morning assembly","All students · Main courtyard","Published","success"],
 ["10:30","Monday","Examination readiness","Exam office · Conference room","Confirmed","success"],
 ["13:15","Wednesday","Fee reminder publication","214 family accounts · Finance","Scheduled","info"],
 ["15:30","Thursday","Sports committee","12 staff · Activity hall","Room review","warning"],
] as const;
const agenda=[
 ["22 Jul · 08:00","Attendance follow-up","48 families · Automatic reminder","Complete","success"],
 ["22 Jul · 10:30","Examination readiness","Exam office · Conference room","Today","info"],
 ["22 Jul · 15:30","Sports committee","12 staff · Activity hall","Today","info"],
 ["26 Jul · 09:00","Assessment 1 begins","Grades 6–10 · Academic block","Published","success"],
 ["28 Jul · 15:00","Parent–teacher meeting","All grades · Assigned rooms","Responses due","warning"],
] as const;
const academic=[
 ["Term 1","12 Jan – 30 Apr 2026","74 teaching days","Completed","success"],
 ["Term 2","10 May – 31 Aug 2026","76 teaching days","Current","info"],
 ["Term 3","13 Sep – 10 Dec 2026","69 teaching days","Published","success"],
 ["Annual examinations","15 Nov – 30 Nov 2026","12 exam days","Draft","warning"],
] as const;
const rooms=[
 ["Conference room","Examination readiness","22 Jul · 10:30–11:30","18 / 24","Confirmed","success"],
 ["Activity hall","Sports committee","22 Jul · 15:30–16:30","12 / 120","Review","warning"],
 ["Auditorium","Parent–teacher briefing","28 Jul · 14:30–15:00","85 / 160","Confirmed","success"],
 ["Science lab 2","Assessment practical","26 Jul · 09:00–12:00","32 / 32","At capacity","info"],
] as const;
function Toolbar({label}:{label:string}){return <div className={styles.toolbar}><label className={styles.search}><MagnifyingGlass size={15}/><input aria-label={`Search ${label}`} placeholder="Search events…" type="search"/></label><button className={styles.toolButton} type="button"><SlidersHorizontal size={15}/>Filters</button></div>}
function Queue({items}:{items:readonly (readonly [string,string,string,string])[]}){return <div className={styles.queueList}>{items.map(([title,detail,state,tone])=><article className={styles.queueItem} key={title}><div><strong>{title}</strong><span>{detail}</span></div><StatusPill tone={tone as StatusTone}>{state}</StatusPill></article>)}</div>}
function Stats(){return <section aria-label="Calendar statistics" className={styles.stats}><StatCard detail="9 are school-wide" icon={<CalendarBlank size={19}/>} label="Events in July" value="14"/><StatCard detail="2 due within seven days" icon={<Clock size={19}/>} label="Academic deadlines" tone="amber" value="6"/><StatCard detail="Next: 28 July at 3:00 PM" icon={<UsersThree size={19}/>} label="Meetings" tone="violet" value="4"/><StatCard detail="1,842 recipients reached" icon={<Bell size={19}/>} label="Reminder delivery" tone="green" value="98.8%"/></section>}
function EventDialog({day,event,onClose,onSave,onDelete}:{day:number;event:CalendarEvent;onClose:()=>void;onSave:(event:CalendarEvent)=>void;onDelete:()=>void}){const[editing,setEditing]=useState(false);const[draft,setDraft]=useState(event);function save(){if(!draft.label.trim())return;onSave({...draft,label:draft.label.trim()});setEditing(false)}return <div aria-modal="true" className={styles.dialogBackdrop} onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}} role="dialog"><section className={styles.eventDialog}><header><div><span>July {day}, 2026</span><h2>{editing?"Edit event":event.label}</h2></div><button aria-label="Close event details" onClick={onClose} type="button"><X size={18}/></button></header>{editing?<div className={styles.dialogForm}><label>Event title<input autoFocus value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><div><label>Time<input type="time" value={draft.time.includes(":")&&draft.time.length===5?draft.time:"09:00"} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><label>Type<select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as CalendarEvent["kind"]})}><option value="event">Event</option><option value="exam">Exam</option><option value="deadline">Deadline</option></select></label></div><label>Location<input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label><label>Audience<input value={draft.audience} onChange={e=>setDraft({...draft,audience:e.target.value})}/></label><label>Description<textarea rows={3} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></div>:<div className={styles.dialogDetails}><div><Clock size={17}/><span><strong>{event.time}</strong>Asia/Dhaka</span></div><div><Buildings size={17}/><span><strong>{event.location}</strong>Location</span></div><div><UsersThree size={17}/><span><strong>{event.audience}</strong>Audience</span></div><p>{event.description}</p></div>}<footer>{editing?<><button className={styles.dialogSecondary} onClick={()=>{setDraft(event);setEditing(false)}} type="button">Cancel</button><button className={styles.dialogPrimary} disabled={!draft.label.trim()} onClick={save} type="button">Save changes</button></>:<><button className={styles.dialogDanger} onClick={()=>{if(window.confirm(`Delete “${event.label}”? This cannot be undone.`))onDelete()}} type="button"><Trash size={15}/>Delete</button><button className={styles.dialogPrimary} onClick={()=>setEditing(true)} type="button"><PencilSimple size={15}/>Edit event</button></>}</footer></section></div>}
function Month({calendarEvents,setCalendarEvents}:{calendarEvents:Record<number,CalendarEvent>;setCalendarEvents:React.Dispatch<React.SetStateAction<Record<number,CalendarEvent>>>}){const[selectedDay,setSelectedDay]=useState<number|null>(null);const selectedEvent=selectedDay===null?undefined:calendarEvents[selectedDay];return <><Stats/><div className={styles.calendarLayout}><Panel className={styles.calendarPanel} description="Asia/Dhaka · School and academic events" title="July 2026"><div className={styles.calendarToolbar}><strong>July 2026</strong><div><button type="button">Today</button><button aria-label="Previous month" type="button">‹</button><button aria-label="Next month" type="button">›</button></div></div><div className={styles.month}>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><div className={styles.dayName} key={day}>{day}</div>)}{days.map((day,index)=>{const outside=index<2||index>32,e=!outside?calendarEvents[day]:undefined;return <div className={`${styles.day} ${outside?styles.outside:""} ${day===22&&!outside?styles.today:""} ${e?styles.eventDay:""}`} key={`${index}-${day}`} onClick={()=>e&&setSelectedDay(day)} onKeyDown={key=>{if(e&&(key.key==="Enter"||key.key===" "))setSelectedDay(day)}} role={e?"button":undefined} tabIndex={e?0:undefined}><b>{day}</b>{e?<div className={`${styles.eventDot} ${e.kind!=="event"?styles[e.kind]:""}`}>{e.label}</div>:null}</div>})}</div></Panel><aside className={styles.stack}><Today/><Panel description="Events needing owner action" title="Publishing queue"><Queue items={[["August school calendar","11 events · audience review incomplete","Draft","warning"],["Parent–teacher meeting","28 invitations have no response","Follow up","info"],["Room conflicts","All upcoming bookings validated","Clear","success"]]}/></Panel></aside></div>{selectedDay!==null&&selectedEvent?<EventDialog day={selectedDay} event={selectedEvent} onClose={()=>setSelectedDay(null)} onDelete={()=>{setCalendarEvents(current=>{const next={...current};delete next[selectedDay];return next});setSelectedDay(null)}} onSave={event=>setCalendarEvents(current=>({...current,[selectedDay]:event}))}/>:null}</>}
function Today(){return <Panel description="Wednesday, 22 July" title="Today"><div className={styles.eventList}>{[["08:00","Attendance follow-up","48 families · automatic reminder"],["10:30","Examination readiness","Exam office · Conference room"],["13:15","Fee reminder publication","214 family accounts · Finance"],["15:30","Sports committee","12 staff · Activity hall"]].map(([time,title,detail])=><article className={styles.eventCard} key={time}><time>{time}</time><div><strong>{title}</strong><span>{detail}</span></div></article>)}</div></Panel>}
function Week(){return <><Stats/><div className={styles.grid}><Panel description="19–25 July 2026 · Asia/Dhaka" title="Weekly schedule"><Toolbar label="week schedule"/><div className={styles.tableWrap}><table aria-label="Weekly schedule" className={styles.table}><thead><tr><th>Time</th><th>Day</th><th>Event</th><th>Audience / location</th><th>Status</th></tr></thead><tbody>{week.map(r=><tr key={`${r[0]}-${r[1]}`}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><StatusPill tone={r[5]}>{r[4]}</StatusPill></td></tr>)}</tbody></table></div></Panel><aside className={styles.stack}><Today/><Panel description="Schedule health this week" title="Weekly readiness"><div className={styles.progressList}><ProgressRow detail="12 of 14 events" label="Audience confirmed" value={86}/><ProgressRow detail="8 of 9 room events" label="Rooms assigned" tone="warning" value={89}/><ProgressRow detail="10 of 10 reminders" label="Reminders scheduled" tone="success" value={100}/></div></Panel></aside></div></>}
function Agenda(){return <><Stats/><div className={styles.grid}><Panel description="Upcoming events in chronological order" title="School agenda"><Toolbar label="agenda"/><div className={styles.agendaList}>{agenda.map(([time,title,detail,state,tone])=><article className={styles.agendaItem} key={`${time}-${title}`}><time>{time}</time><i/><div><strong>{title}</strong><span>{detail}</span></div><StatusPill tone={tone}>{state}</StatusPill></article>)}</div></Panel><aside className={styles.stack}><Panel description="Upcoming workload" title="Agenda summary"><div className={styles.progressList}><ProgressRow detail="14 scheduled events" label="July" value={78}/><ProgressRow detail="11 draft or published events" label="August" value={61}/><ProgressRow detail="4 school-wide deadlines" label="Next 30 days" tone="warning" value={40}/></div></Panel><Panel description="Items requiring action" title="Agenda exceptions"><Queue items={[["Parent meeting responses","28 still unconfirmed","Follow up","warning"],["Sports committee room","Capacity review required","Review","info"],["Assessment notice","All recipients reached","Complete","success"]]}/></Panel></aside></div></>}
function Academic(){return <><section className={styles.stats}><StatCard detail="219 approved teaching days" icon={<CalendarBlank size={19}/>} label="Academic year" value="2026"/><StatCard detail="10 May – 31 August" icon={<Clock size={19}/>} label="Current term" tone="violet" value="Term 2"/><StatCard detail="Including public holidays" icon={<WarningCircle size={19}/>} label="Non-teaching days" tone="amber" value="31"/><StatCard detail="All term dates published" icon={<CheckCircle size={19}/>} label="Calendar readiness" tone="green" value="96%"/></section><div className={styles.grid}><Panel description="Terms, examinations, holidays, and closures" title="Academic year structure"><div className={styles.tableWrap}><table aria-label="Academic calendar" className={styles.table}><thead><tr><th>Period</th><th>Dates</th><th>Duration</th><th>Status</th></tr></thead><tbody>{academic.map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td>{r[2]}</td><td><StatusPill tone={r[4]}>{r[3]}</StatusPill></td></tr>)}</tbody></table></div></Panel><aside className={styles.stack}><Panel description="Academic day allocation" title="Year composition"><div className={styles.progressList}><ProgressRow detail="219 approved days" label="Teaching days" tone="success" value={79}/><ProgressRow detail="24 assessment days" label="Examinations" value={9}/><ProgressRow detail="31 closure days" label="Holidays and breaks" value={12}/></div></Panel><Panel description="Dates requiring publication" title="Calendar governance"><Queue items={[["Annual examination plan","Audience review incomplete","Draft","warning"],["Term 3 holidays","Approved and published","Complete","success"],["2027 academic year","Planning opens 1 September","Upcoming","info"]]}/></Panel></aside></div></>}
function Rooms(){return <><section className={styles.stats}><StatCard detail="Bookable shared spaces" icon={<Buildings size={19}/>} label="Managed rooms" value="18"/><StatCard detail="Across today’s schedule" icon={<CalendarBlank size={19}/>} label="Bookings today" tone="violet" value="12"/><StatCard detail="Require capacity review" icon={<WarningCircle size={19}/>} label="Booking conflicts" tone="amber" value="1"/><StatCard detail="During school hours" icon={<CheckCircle size={19}/>} label="Room utilization" tone="green" value="68%"/></section><div className={styles.grid}><Panel description="Upcoming shared-space reservations" title="Room booking schedule"><Toolbar label="room bookings"/><div className={styles.tableWrap}><table aria-label="Room bookings" className={styles.table}><thead><tr><th>Room</th><th>Event</th><th>Date & time</th><th>Capacity</th><th>Status</th></tr></thead><tbody>{rooms.map(r=><tr key={`${r[0]}-${r[2]}`}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><StatusPill tone={r[5]}>{r[4]}</StatusPill></td></tr>)}</tbody></table></div></Panel><aside className={styles.stack}><Panel description="Availability by room group" title="Space utilization"><div className={styles.progressList}><ProgressRow detail="6 of 8 periods booked" label="Meeting rooms" value={75}/><ProgressRow detail="5 of 8 periods booked" label="Halls and auditorium" value={63}/><ProgressRow detail="7 of 8 periods booked" label="Laboratories" tone="warning" value={88}/></div></Panel><Panel description="Booking checks" title="Room operations"><Queue items={[["Activity hall","Capacity setup needs review","Review","warning"],["Science lab 2","At capacity for assessment","Monitor","info"],["Conference room","All upcoming bookings valid","Clear","success"]]}/></Panel></aside></div></>}
export function CalendarWorkspace(){const[active,setActive]=useState<Tab>("Month");const[calendarEvents,setCalendarEvents]=useState(initialEvents);return <div className={styles.page}><PageHeader action="Create event" description="Plan academic dates, meetings, holidays, deadlines, audiences, rooms, and reminder delivery from one shared school calendar." eyebrow="Communications / Calendar" secondaryAction="Calendar settings" title="School calendar"/><nav aria-label="Calendar views" className={styles.tabs} role="tablist">{tabs.map(t=><button aria-selected={active===t} className={active===t?styles.activeTab:""} key={t} onClick={()=>setActive(t)} role="tab" type="button">{t}</button>)}</nav><section aria-live="polite" role="tabpanel">{active==="Month"?<Month calendarEvents={calendarEvents} setCalendarEvents={setCalendarEvents}/>:active==="Week"?<Week/>:active==="Agenda"?<Agenda/>:active==="Academic calendar"?<Academic/>:<Rooms/>}</section></div>}
