import { Bell, CalendarBlank, Clock, UsersThree } from "@phosphor-icons/react/dist/ssr";
import { PageHeader, Panel, StatCard, StatusPill } from "./operations-ui";
import styles from "./core-operations.module.css";

const days = [29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,1,2];
const events: Record<number, { label: string; kind?: string }> = { 8:{label:"Staff meeting"}, 14:{label:"Result review",kind:"exam"}, 22:{label:"Fee reminder",kind:"deadline"}, 26:{label:"Assessment 1",kind:"exam"}, 28:{label:"Family meeting"}, 31:{label:"Fee deadline",kind:"deadline"} };

export function CalendarWorkspace() {
  return <div className={styles.page}><PageHeader action="Create event" description="Plan academic dates, meetings, holidays, deadlines, audiences, rooms, and reminder delivery from one shared school calendar." eyebrow="Communications / Calendar" secondaryAction="Calendar settings" title="School calendar" />
    <nav aria-label="Calendar views" className={styles.tabs}>{["Month","Week","Agenda","Academic calendar","Room bookings"].map((tab,index)=><button className={index===0?styles.activeTab:""} key={tab} type="button">{tab}</button>)}</nav>
    <section aria-label="Calendar statistics" className={styles.stats}><StatCard detail="9 are school-wide" icon={<CalendarBlank size={19}/>} label="Events in July" value="14"/><StatCard detail="2 due within seven days" icon={<Clock size={19}/>} label="Academic deadlines" tone="amber" value="6"/><StatCard detail="Next: 28 July at 3:00 PM" icon={<UsersThree size={19}/>} label="Meetings" tone="violet" value="4"/><StatCard detail="1,842 recipients reached" icon={<Bell size={19}/>} label="Reminder delivery" tone="green" value="98.8%"/></section>
    <div className={styles.calendarLayout}><Panel className={styles.calendarPanel} description="Asia/Dhaka · School and academic events" title="July 2026"><div className={styles.calendarToolbar}><strong>July 2026</strong><div><button type="button">Today</button><button aria-label="Previous month" type="button">‹</button><button aria-label="Next month" type="button">›</button></div></div><div className={styles.month}>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><div className={styles.dayName} key={day}>{day}</div>)}{days.map((day,index)=>{const isOutside=index<2||index>32;const event=!isOutside?events[day]:undefined;return <div className={`${styles.day} ${isOutside?styles.outside:""} ${day===22&&!isOutside?styles.today:""}`} key={`${index}-${day}`}><b>{day}</b>{event?<div className={`${styles.eventDot} ${event.kind?styles[event.kind]:""}`}>{event.label}</div>:null}</div>})}</div></Panel>
      <aside className={styles.stack}><Panel action="View agenda" description="Wednesday, 22 July" title="Today"><div className={styles.eventList}>{[["08:00","Attendance follow-up","48 families · automatic reminder"],["10:30","Examination readiness","Exam office · Conference room"],["13:15","Fee reminder publication","214 family accounts · Finance"],["15:30","Sports committee","12 staff · Activity hall"]].map(([time,title,detail])=><article className={styles.eventCard} key={`${time}-${title}`}><time>{time}</time><div><strong>{title}</strong><span>{detail}</span></div></article>)}</div></Panel><Panel description="Events needing owner action" title="Publishing queue"><div className={styles.queueList}><article className={styles.queueItem}><div><strong>August school calendar</strong><span>11 events · audience review incomplete</span></div><StatusPill tone="warning">Draft</StatusPill></article><article className={styles.queueItem}><div><strong>Parent–teacher meeting</strong><span>28 invitations have no response</span></div><StatusPill tone="info">Follow up</StatusPill></article><article className={styles.queueItem}><div><strong>Room conflicts</strong><span>All upcoming room bookings validated</span></div><StatusPill tone="success">Clear</StatusPill></article></div></Panel></aside></div>
  </div>;
}
