import { BookOpen, CheckCircle, Clock, GraduationCap, IdentificationBadge, MagnifyingGlass, SlidersHorizontal, Student, TrendUp, UsersThree, WarningCircle } from "@phosphor-icons/react/dist/ssr";
import { MoreActionsButton } from "@/components/ui/more-actions-button";
import { PageHeader, Panel, ProgressRow, StatCard, StatusPill } from "./operations-ui";
import styles from "./core-operations.module.css";

const people = [
  ["Ayesha Rahman", "STU-2026-0142", "Student · Grade 8A", "Masud Rahman", "Verified", "success"],
  ["Farhana Akter", "EMP-0084", "Senior teacher · Mathematics", "Staff profile", "Active", "success"],
  ["Masud Karim", "GAR-1048", "Guardian · 2 learners", "Email + mobile", "Verified", "info"],
  ["Nafisa Islam", "STU-2026-0189", "Student · Grade 6B", "Kamal Akter", "Review", "warning"],
] as const;

const students = [
  ["Ayesha Rahman", "STU-2026-0142", "Grade 8 · A", "Masud Rahman", "100%", "Active", "success"],
  ["Rafi Islam", "STU-2026-0158", "Grade 9 · B", "Tasnim Islam", "96%", "Active", "success"],
  ["Nafisa Akter", "STU-2026-0189", "Grade 6 · B", "Kamal Akter", "82%", "Documents due", "warning"],
  ["Saad Hasan", "STU-2026-0201", "Grade 10 · C", "Rashida Hasan", "100%", "Active", "success"],
  ["Maya Chowdhury", "STU-2026-0208", "Grade 7 · A", "Amin Chowdhury", "91%", "Review", "info"],
] as const;

const teachers = [
  ["Farhana Akter", "EMP-0084", "Mathematics", "26 / 28", "Grade 8A", "Teaching", "success"],
  ["Rashid Hasan", "EMP-0061", "Science", "24 / 28", "Grade 9B", "Teaching", "success"],
  ["Nadia Rahman", "EMP-0092", "English", "22 / 26", "Grade 7A", "On leave", "warning"],
  ["Mahmud Karim", "EMP-0047", "Bangla", "25 / 28", "Grade 10C", "Teaching", "success"],
] as const;

function DirectoryToolbar({ label }: { label: string }) { return <div className={styles.toolbar}><label className={styles.search}><MagnifyingGlass size={15} /><input aria-label={`Search ${label}`} placeholder="Search name or ID…" type="search" /></label><button className={styles.toolButton} type="button"><SlidersHorizontal size={15} />Filters</button></div>; }

export function PeopleWorkspace() {
  return <div className={styles.page}><PageHeader action="Add person" description="Maintain one trusted identity record for every learner, guardian, teacher, and employee—with verified relationships and contactability." eyebrow="People / Directory" title="People directory" />
    <section aria-label="Directory statistics" className={styles.stats}><StatCard detail="Across 38 active sections" icon={<Student size={19} />} label="Students" value="1,284" /><StatCard detail="1.5 linked per learner" icon={<UsersThree size={19} />} label="Guardians" tone="green" value="1,946" /><StatCard detail="84 available today" icon={<GraduationCap size={19} />} label="Teachers" tone="violet" value="86" /><StatCard detail="93.1% fully verified" icon={<CheckCircle size={19} />} label="Directory health" tone="amber" value="93%" /></section>
    <div className={styles.grid}><div className={styles.stack}><Panel action="Open full directory" description="Browse by relationship to the school" title="Directory groups"><div className={styles.directoryTypes}>{[[<Student key="s" size={19}/>,"Students","Enrolled learners","1,284"],[<UsersThree key="g" size={19}/>,"Guardians","Verified family contacts","1,946"],[<GraduationCap key="t" size={19}/>,"Teachers","Teaching workforce","86"],[<IdentificationBadge key="e" size={19}/>,"Employees","Operations and support","46"]].map(([icon,title,detail,count])=><article className={styles.typeCard} key={String(title)}><div>{icon}</div><div><strong>{title}</strong><span>{detail}</span></div><b>{count}</b></article>)}</div></Panel>
      <Panel description="Profiles changed during the last seven days" title="Recently updated people"><DirectoryToolbar label="people"/><div className={styles.tableWrap}><table aria-label="Recently updated people" className={styles.table}><thead><tr><th>Person</th><th>School ID</th><th>Role</th><th>Relationship / contact</th><th>Record state</th><th>Actions</th></tr></thead><tbody>{people.map(row=><tr key={row[1]}><td><div className={styles.person}><strong>{row[0]}</strong><span>Greenfield High School</span></div></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><StatusPill tone={row[5]}>{row[4]}</StatusPill></td><td className={styles.moreCell}><MoreActionsButton label={`Actions for ${row[0]}`}/></td></tr>)}</tbody></table></div></Panel></div>
      <aside className={styles.stack}><Panel description="Completeness by critical data group" title="Record quality"><div className={styles.progressList}><ProgressRow detail="2,893 of 3,116 people" label="Verified mobile or email" value={93}/><ProgressRow detail="8 relationships need evidence" label="Guardian relationships" tone="warning" value={98}/><ProgressRow detail="34 profiles missing fields" label="Required identity fields" value={97}/><ProgressRow detail="12 consent reviews due" label="Communication consent" tone="success" value={95}/></div></Panel><Panel action="Review queue" description="Identity issues requiring a decision" title="Data stewardship"><div className={styles.queueList}>{[["Possible duplicate profiles","5 record pairs matched by identity data","Review","warning"],["Guardian relationship evidence","8 links await verification","Pending","info"],["Unreachable family contacts","17 contacts failed twice","Action","danger"]].map(([title,detail,status,tone])=><article className={styles.queueItem} key={title}><div><strong>{title}</strong><span>{detail}</span></div><StatusPill tone={tone as "warning"|"info"|"danger"}>{status}</StatusPill></article>)}</div></Panel></aside></div>
  </div>;
}

export function StudentsWorkspace() {
  return <div className={styles.page}><PageHeader action="Enroll student" description="Manage each learner from admission through active enrollment, family relationships, required documents, transfers, and withdrawal." eyebrow="People / Students" secondaryAction="Import roster" title="Student records" />
    <nav aria-label="Student sections" className={styles.tabs}>{["Active students","Admissions","Enrollment changes","Documents","Alumni"].map((tab,index)=><button className={index===0?styles.activeTab:""} key={tab} type="button">{tab}</button>)}</nav>
    <section aria-label="Student statistics" className={styles.stats}><StatCard detail="28 joined this academic year" icon={<Student size={19}/>} label="Active enrollment" value="1,284"/><StatCard detail="Against 1,490 approved seats" icon={<TrendUp size={19}/>} label="Capacity used" tone="green" value="86.2%"/><StatCard detail="6 await required documents" icon={<Clock size={19}/>} label="Admissions in progress" tone="violet" value="18"/><StatCard detail="Transfers, holds, and reviews" icon={<WarningCircle size={19}/>} label="Lifecycle exceptions" tone="amber" value="12"/></section>
    <div className={styles.grid}><div className={styles.stack}><Panel description="2025–2026 academic year · approved section capacity" title="Enrollment by grade"><div className={styles.progressList}><ProgressRow detail="214 of 240 seats · 7 sections" label="Grades 1–3" value={89}/><ProgressRow detail="376 of 450 seats · 12 sections" label="Grades 4–6" value={84}/><ProgressRow detail="418 of 480 seats · 13 sections" label="Grades 7–9" value={87}/><ProgressRow detail="276 of 320 seats · 6 sections" label="Grade 10" value={86}/></div></Panel><Panel description="Active enrollment · Academic year 2025–2026" title="Student roster"><DirectoryToolbar label="students"/><div className={styles.tableWrap}><table aria-label="Student roster" className={styles.table}><thead><tr><th>Student</th><th>Class & section</th><th>Primary guardian</th><th>Profile</th><th>Enrollment</th><th>Actions</th></tr></thead><tbody>{students.map(row=><tr key={row[1]}><td><div className={styles.person}><strong>{row[0]}</strong><span>{row[1]}</span></div></td><td>{row[2]}</td><td>{row[3]}</td><td>{row[4]}</td><td><StatusPill tone={row[6]}>{row[5]}</StatusPill></td><td className={styles.moreCell}><MoreActionsButton label={`Actions for ${row[0]}`}/></td></tr>)}</tbody></table></div></Panel></div>
      <aside className={styles.stack}><Panel description="Current admission pipeline" title="Enrollment lifecycle"><div className={styles.funnel}>{[["Applications received","42"],["Eligibility reviewed","31"],["Offers accepted","24"],["Enrollment completed","18"]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></Panel><Panel action="Open document desk" description="Items blocking complete student files" title="Document exceptions"><div className={styles.queueList}>{[["Birth registration","4 students","Required","danger"],["Previous school record","2 students","Due","warning"],["Guardian identity evidence","3 relationships","Review","info"]].map(([title,detail,status,tone])=><article className={styles.queueItem} key={title}><div><strong>{title}</strong><span>{detail}</span></div><StatusPill tone={tone as "danger"|"warning"|"info"}>{status}</StatusPill></article>)}</div></Panel></aside></div>
  </div>;
}

export function TeachersWorkspace() {
  return <div className={styles.page}><PageHeader action="Add teacher" description="Coordinate teacher profiles, teaching assignments, weekly workload, leave coverage, substitutions, and contract readiness." eyebrow="People / Teachers" secondaryAction="Manage assignments" title="Teaching workforce" />
    <nav aria-label="Teacher sections" className={styles.tabs}>{["Workforce overview","Directory","Subject assignments","Availability","Contracts"].map((tab,index)=><button className={index===0?styles.activeTab:""} key={tab} type="button">{tab}</button>)}</nav>
    <section aria-label="Teacher statistics" className={styles.stats}><StatCard detail="2 on approved leave" icon={<GraduationCap size={19}/>} label="Active teachers" value="84 / 86"/><StatCard detail="Approved range is 22–28" icon={<Clock size={19}/>} label="Average weekly load" tone="violet" value="24.6"/><StatCard detail="4 assignments remain open" icon={<BookOpen size={19}/>} label="Subject coverage" tone="green" value="96.9%"/><StatCard detail="Within the next 60 days" icon={<WarningCircle size={19}/>} label="Contracts expiring" tone="amber" value="3"/></section>
    <div className={styles.grid}><div className={styles.stack}><Panel description="Wednesday, 22 July · availability and coverage" title="Today’s teaching operations"><div className={styles.agendaList}>{[["08:00","Morning attendance review","Class teachers · 38 sections","Complete","success"],["09:30","Grade 8A mathematics","Farhana Akter · Room 204","In class","info"],["11:15","Science substitution","Grade 9B · Lab 2","Unassigned","danger"],["14:10","Department planning","English department · Room 108","Scheduled","neutral"]].map(([time,title,detail,status,tone])=><article className={styles.agendaItem} key={`${time}-${title}`}><time>{time}</time><i/><div><strong>{title}</strong><span>{detail}</span></div><StatusPill tone={tone as "success"|"info"|"danger"|"neutral"}>{status}</StatusPill></article>)}</div></Panel><Panel description="Current timetable cycle · target ranges include non-contact allocation" title="Teacher workload"><DirectoryToolbar label="teachers"/><div className={styles.tableWrap}><table aria-label="Teacher workload" className={styles.table}><thead><tr><th>Teacher</th><th>Department</th><th>Weekly periods</th><th>Homeroom</th><th>Today</th><th>Actions</th></tr></thead><tbody>{teachers.map(row=><tr key={row[1]}><td><div className={styles.person}><strong>{row[0]}</strong><span>{row[1]}</span></div></td><td>{row[2]}</td><td><div className={styles.person}><strong>{row[3]}</strong><div className={styles.workloadBar}><i style={{width:`${Number(row[3].split(" ")[0])/28*100}%`}}/></div></div></td><td>{row[4]}</td><td><StatusPill tone={row[6]}>{row[5]}</StatusPill></td><td className={styles.moreCell}><MoreActionsButton label={`Actions for ${row[0]}`}/></td></tr>)}</tbody></table></div></Panel></div>
      <aside className={styles.stack}><Panel action="Open coverage desk" description="Leave and substitution decisions" title="Coverage required"><div className={styles.queueList}>{[["Grade 9B · Science","Period 4 today · Nadia Rahman on leave","Unassigned","danger"],["Grade 6A · English","Period 2 tomorrow · training leave","2 candidates","warning"],["Grade 10C · Bangla","Friday · timetable conflict","Review","info"]].map(([title,detail,status,tone])=><article className={styles.queueItem} key={title}><div><strong>{title}</strong><span>{detail}</span></div><StatusPill tone={tone as "danger"|"warning"|"info"}>{status}</StatusPill></article>)}</div></Panel><Panel description="Assignment completeness by department" title="Subject coverage"><div className={styles.progressList}><ProgressRow detail="46 of 46 assignments" label="Mathematics" tone="success" value={100}/><ProgressRow detail="41 of 43 assignments" label="Science" tone="warning" value={95}/><ProgressRow detail="38 of 39 assignments" label="English" value={97}/><ProgressRow detail="34 of 35 assignments" label="Bangla" value={97}/></div></Panel></aside></div>
  </div>;
}
