"use client";

import { useState } from "react";
import { BookOpen, Briefcase, CalendarCheck, CheckCircle, Clock, FileText, GraduationCap, MagnifyingGlass, SlidersHorizontal, UsersThree, WarningCircle } from "@phosphor-icons/react";
import { MoreActionsButton } from "@/components/ui/more-actions-button";
import { PageHeader, Panel, ProgressRow, StatCard, StatusPill, type StatusTone } from "./operations-ui";
import styles from "./core-operations.module.css";

type Tab = "Workforce overview" | "Directory" | "Subject assignments" | "Availability" | "Contracts";
const tabs: Tab[] = ["Workforce overview", "Directory", "Subject assignments", "Availability", "Contracts"];

const teachers = [
  ["Farhana Akter", "EMP-0084", "Mathematics", "26 / 28", "Grade 8A", "Teaching", "success"],
  ["Rashid Hasan", "EMP-0061", "Science", "24 / 28", "Grade 9B", "Teaching", "success"],
  ["Nadia Rahman", "EMP-0092", "English", "22 / 26", "Grade 7A", "On leave", "warning"],
  ["Mahmud Karim", "EMP-0047", "Bangla", "25 / 28", "Grade 10C", "Teaching", "success"],
] as const;
const assignments = [
  ["Farhana Akter", "Mathematics", "Grade 8A, 8B", "18", "Complete", "success"],
  ["Rashid Hasan", "Science", "Grade 9A, 9B", "16", "Complete", "success"],
  ["Nadia Rahman", "English", "Grade 7A, 7B", "14", "Cover needed", "warning"],
  ["Mahmud Karim", "Bangla", "Grade 10A, 10C", "17", "Conflict", "danger"],
] as const;
const availability = [
  ["Nadia Rahman", "Annual leave", "22–26 Jul 2026", "5 days", "Approved", "success"],
  ["Sadia Sultana", "Training", "27 Jul 2026", "1 day", "Cover pending", "warning"],
  ["Jamil Hossain", "Medical leave", "28–29 Jul 2026", "2 days", "Review", "info"],
  ["Farhana Akter", "Personal leave", "4 Aug 2026", "1 day", "Requested", "neutral"],
] as const;
const contracts = [
  ["Mahmud Karim", "EMP-0047", "Permanent", "31 Jul 2026", "Renewal due", "warning"],
  ["Nadia Rahman", "EMP-0092", "Fixed term", "15 Aug 2026", "Review", "info"],
  ["Farhana Akter", "EMP-0084", "Permanent", "30 Jun 2027", "Active", "success"],
  ["Rashid Hasan", "EMP-0061", "Permanent", "30 Jun 2027", "Active", "success"],
] as const;

function Toolbar({ label }: { label: string }) { return <div className={styles.toolbar}><label className={styles.search}><MagnifyingGlass size={15}/><input aria-label={`Search ${label}`} placeholder="Search name or ID…" type="search"/></label><button className={styles.toolButton} type="button"><SlidersHorizontal size={15}/>Filters</button></div>; }
function Queue({ items }: { items: readonly (readonly [string,string,string,string])[] }) { return <div className={styles.queueList}>{items.map(([title,detail,status,tone])=><article className={styles.queueItem} key={title}><div><strong>{title}</strong><span>{detail}</span></div><StatusPill tone={tone as StatusTone}>{status}</StatusPill></article>)}</div>; }
function TeacherTable({ title = "Teacher workload", description = "Current timetable cycle · target ranges include non-contact allocation" }: { title?: string; description?: string }) { return <Panel description={description} title={title}><Toolbar label="teachers"/><div className={styles.tableWrap}><table aria-label={title} className={styles.table}><thead><tr><th>Teacher</th><th>Department</th><th>Weekly periods</th><th>Homeroom</th><th>Today</th><th>Actions</th></tr></thead><tbody>{teachers.map(row=><tr key={row[1]}><td><div className={styles.person}><strong>{row[0]}</strong><span>{row[1]}</span></div></td><td>{row[2]}</td><td><div className={styles.person}><strong>{row[3]}</strong><div className={styles.workloadBar}><i style={{width:`${Number(row[3].split(" ")[0])/28*100}%`}}/></div></div></td><td>{row[4]}</td><td><StatusPill tone={row[6]}>{row[5]}</StatusPill></td><td className={styles.moreCell}><MoreActionsButton label={`Actions for ${row[0]}`}/></td></tr>)}</tbody></table></div></Panel>; }

function Overview() { return <><section className={styles.stats}><StatCard detail="2 on approved leave" icon={<GraduationCap size={19}/>} label="Active teachers" value="84 / 86"/><StatCard detail="Approved range is 22–28" icon={<Clock size={19}/>} label="Average weekly load" tone="violet" value="24.6"/><StatCard detail="4 assignments remain open" icon={<BookOpen size={19}/>} label="Subject coverage" tone="green" value="96.9%"/><StatCard detail="Within the next 60 days" icon={<WarningCircle size={19}/>} label="Contracts expiring" tone="amber" value="3"/></section><div className={styles.grid}><div className={styles.stack}><Panel description="Saturday, 25 July · availability and coverage" title="Today’s teaching operations"><div className={styles.agendaList}>{[["08:00","Morning attendance review","Class teachers · 38 sections","Complete","success"],["09:30","Grade 8A mathematics","Farhana Akter · Room 204","In class","info"],["11:15","Science substitution","Grade 9B · Lab 2","Unassigned","danger"],["14:10","Department planning","English department · Room 108","Scheduled","neutral"]].map(([time,title,detail,status,tone])=><article className={styles.agendaItem} key={`${time}-${title}`}><time>{time}</time><i/><div><strong>{title}</strong><span>{detail}</span></div><StatusPill tone={tone as StatusTone}>{status}</StatusPill></article>)}</div></Panel><TeacherTable/></div><aside className={styles.stack}><Panel action="Open coverage desk" description="Leave and substitution decisions" title="Coverage required"><Queue items={[["Grade 9B · Science","Period 4 today · Nadia Rahman on leave","Unassigned","danger"],["Grade 6A · English","Period 2 tomorrow · training leave","2 candidates","warning"],["Grade 10C · Bangla","Friday · timetable conflict","Review","info"]]}/></Panel><Panel description="Assignment completeness by department" title="Subject coverage"><div className={styles.progressList}><ProgressRow detail="46 of 46 assignments" label="Mathematics" tone="success" value={100}/><ProgressRow detail="41 of 43 assignments" label="Science" tone="warning" value={95}/><ProgressRow detail="38 of 39 assignments" label="English" value={97}/><ProgressRow detail="34 of 35 assignments" label="Bangla" value={97}/></div></Panel></aside></div></>; }

function Directory() { return <><section className={styles.stats}><StatCard detail="Across 8 departments" icon={<UsersThree size={19}/>} label="Teacher records" value="86"/><StatCard detail="84 currently teaching" icon={<CheckCircle size={19}/>} label="Active profiles" tone="green" value="97.7%"/><StatCard detail="Required identity and contact fields" icon={<FileText size={19}/>} label="Profile completeness" tone="violet" value="94.2%"/><StatCard detail="Need verification or correction" icon={<WarningCircle size={19}/>} label="Record exceptions" tone="amber" value="5"/></section><div className={styles.grid}><TeacherTable description="All active and leave-status teaching staff" title="Teacher directory"/><aside className={styles.stack}><Panel description="Workforce by department" title="Department distribution"><div className={styles.progressList}><ProgressRow detail="18 teachers" label="Languages" value={21}/><ProgressRow detail="16 teachers" label="Mathematics" value={19}/><ProgressRow detail="15 teachers" label="Science" value={17}/><ProgressRow detail="37 across other departments" label="Other subjects" value={43}/></div></Panel><Panel description="Profiles requiring data stewardship" title="Directory quality"><Queue items={[["Missing emergency contact","2 teachers","Action","danger"],["Identity verification due","1 teacher","Verify","warning"],["Duplicate contact details","2 record pairs","Review","info"]]}/></Panel></aside></div></>; }

function Assignments() { return <><section className={styles.stats}><StatCard detail="Across all grades and sections" icon={<BookOpen size={19}/>} label="Teaching assignments" value="162"/><StatCard detail="158 assignments staffed" icon={<CheckCircle size={19}/>} label="Coverage" tone="green" value="97.5%"/><StatCard detail="Need an assigned teacher" icon={<WarningCircle size={19}/>} label="Open assignments" tone="amber" value="4"/><StatCard detail="Overlaps or workload limits" icon={<Clock size={19}/>} label="Conflicts" tone="violet" value="3"/></section><div className={styles.grid}><Panel description="Current timetable cycle · teacher-to-subject allocation" title="Subject assignments"><Toolbar label="assignments"/><div className={styles.tableWrap}><table aria-label="Subject assignments" className={styles.table}><thead><tr><th>Teacher</th><th>Subject</th><th>Classes</th><th>Periods</th><th>Status</th><th>Actions</th></tr></thead><tbody>{assignments.map(row=><tr key={`${row[0]}-${row[1]}`}><td><strong>{row[0]}</strong></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><StatusPill tone={row[5]}>{row[4]}</StatusPill></td><td><MoreActionsButton label={`Actions for ${row[0]}`}/></td></tr>)}</tbody></table></div></Panel><aside className={styles.stack}><Panel description="Assignments without confirmed coverage" title="Open coverage"><Queue items={[["Grade 9B · Science","4 weekly periods","Unassigned","danger"],["Grade 6A · English","5 weekly periods","2 candidates","warning"],["Grade 10C · Bangla","3-period conflict","Resolve","info"]]}/></Panel><Panel description="Approved load is 22–28 periods" title="Workload balance"><div className={styles.progressList}><ProgressRow detail="72 teachers within range" label="Balanced load" tone="success" value={84}/><ProgressRow detail="8 teachers below range" label="Under allocated" value={9}/><ProgressRow detail="6 teachers above range" label="Over allocated" tone="warning" value={7}/></div></Panel></aside></div></>; }

function Availability() { return <><section className={styles.stats}><StatCard detail="Available for teaching today" icon={<CalendarCheck size={19}/>} label="Present" value="82"/><StatCard detail="Approved leave today" icon={<Clock size={19}/>} label="On leave" tone="violet" value="2"/><StatCard detail="Today and next 7 days" icon={<UsersThree size={19}/>} label="Substitutions needed" tone="amber" value="5"/><StatCard detail="Confirmed cover assignments" icon={<CheckCircle size={19}/>} label="Coverage arranged" tone="green" value="80%"/></section><div className={styles.grid}><Panel description="Leave, training, and availability affecting teaching" title="Availability calendar"><Toolbar label="availability"/><div className={styles.tableWrap}><table aria-label="Teacher availability" className={styles.table}><thead><tr><th>Teacher</th><th>Reason</th><th>Dates</th><th>Duration</th><th>Status</th><th>Actions</th></tr></thead><tbody>{availability.map(row=><tr key={`${row[0]}-${row[2]}`}><td><strong>{row[0]}</strong></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><StatusPill tone={row[5]}>{row[4]}</StatusPill></td><td><MoreActionsButton label={`Actions for ${row[0]}`}/></td></tr>)}</tbody></table></div></Panel><aside className={styles.stack}><Panel description="Upcoming classes affected by absence" title="Coverage desk"><Queue items={[["Grade 9B · Science","Today, period 4","Unassigned","danger"],["Grade 6A · English","27 Jul, period 2","2 candidates","warning"],["Grade 7A · English","28 Jul, periods 1 & 3","Planned","success"]]}/></Panel><Panel description="Leave decisions this month" title="Leave operations"><div className={styles.progressList}><ProgressRow detail="14 of 16 requests decided" label="Requests processed" value={88}/><ProgressRow detail="12 approved absences covered" label="Coverage confirmed" tone="success" value={92}/><ProgressRow detail="2 awaiting evidence" label="Evidence complete" tone="warning" value={86}/></div></Panel></aside></div></>; }

function Contracts() { return <><section className={styles.stats}><StatCard detail="Permanent and fixed-term staff" icon={<Briefcase size={19}/>} label="Active contracts" value="86"/><StatCard detail="Within the next 60 days" icon={<WarningCircle size={19}/>} label="Expiring soon" tone="amber" value="3"/><StatCard detail="Required evidence attached" icon={<FileText size={19}/>} label="Document complete" tone="violet" value="97.7%"/><StatCard detail="Completed for current cycle" icon={<CheckCircle size={19}/>} label="Reviews signed" tone="green" value="81 / 86"/></section><div className={styles.grid}><Panel description="Employment terms, review dates, and renewal status" title="Contract register"><Toolbar label="contracts"/><div className={styles.tableWrap}><table aria-label="Teacher contracts" className={styles.table}><thead><tr><th>Teacher</th><th>Contract type</th><th>Review / end date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{contracts.map(row=><tr key={row[1]}><td><div className={styles.person}><strong>{row[0]}</strong><span>{row[1]}</span></div></td><td>{row[2]}</td><td>{row[3]}</td><td><StatusPill tone={row[5]}>{row[4]}</StatusPill></td><td><MoreActionsButton label={`Actions for ${row[0]}`}/></td></tr>)}</tbody></table></div></Panel><aside className={styles.stack}><Panel description="Items requiring HR or leadership action" title="Renewal queue"><Queue items={[["Mahmud Karim","Ends 31 Jul · decision due","Urgent","danger"],["Nadia Rahman","Ends 15 Aug · review open","Review","warning"],["Teaching addenda","2 signatures outstanding","Action","info"]]}/></Panel><Panel description="Current workforce documentation" title="Contract readiness"><div className={styles.progressList}><ProgressRow detail="86 of 86 records" label="Signed agreement" tone="success" value={100}/><ProgressRow detail="84 of 86 records" label="Identity evidence" value={98}/><ProgressRow detail="81 of 86 records" label="Performance review" tone="warning" value={94}/></div></Panel></aside></div></>; }

export function TeachersWorkspace() { const [activeTab,setActiveTab]=useState<Tab>("Workforce overview"); return <div className={styles.page}><PageHeader action="Add teacher" description="Coordinate teacher profiles, teaching assignments, weekly workload, leave coverage, substitutions, and contract readiness." eyebrow="People / Teachers" secondaryAction="Manage assignments" title="Teaching workforce"/><nav aria-label="Teacher sections" className={styles.tabs} role="tablist">{tabs.map(tab=><button aria-controls={`teacher-panel-${tab.toLowerCase().replaceAll(" ","-")}`} aria-selected={activeTab===tab} className={activeTab===tab?styles.activeTab:""} key={tab} onClick={()=>setActiveTab(tab)} role="tab" type="button">{tab}</button>)}</nav><section aria-live="polite" id={`teacher-panel-${activeTab.toLowerCase().replaceAll(" ","-")}`} role="tabpanel">{activeTab==="Workforce overview"?<Overview/>:activeTab==="Directory"?<Directory/>:activeTab==="Subject assignments"?<Assignments/>:activeTab==="Availability"?<Availability/>:<Contracts/>}</section></div>; }
