import { CalendarBlank, CheckCircle, Exam, FileText, Student, WarningCircle } from "@phosphor-icons/react/dist/ssr";
import type { Metadata } from "next";
import { CircularProgress } from "@/components/ui/circular-progress";
import { AcademicPageHeader, AcademicStat, StatusPill, WorkspacePanel } from "@/features/academics/academic-ui";
import styles from "@/features/academics/academics.module.css";

export const metadata: Metadata = { title: "Exams and results" };
const exams = [{ name: "Mid-term Examination", grades: "Grades 6–10", date: "02–14 Aug 2026", progress: "32 / 48", status: "Marks entry" }, { name: "Primary Assessment 1", grades: "Grades 1–5", date: "26–30 Jul 2026", progress: "18 / 18", status: "Moderation" }, { name: "Final Examination 2025–26", grades: "All grades", date: "Completed", progress: "64 / 64", status: "Published" }, { name: "Practice Assessment", grades: "Grade 10", date: "05 Sep 2026", progress: "0 / 8", status: "Draft" }];
export default function ExamsPage() { return <div className={styles.page}><AcademicPageHeader action="Create examination" description="Plan assessments, track marks entry, moderate outcomes, and publish results safely." title="Exams & results" /><section className={styles.hero}><div className={styles.heroCopy}><span>Mid-term examination</span><h2>Marks entry is 67% complete.</h2><p>Four subjects are approaching their submission deadline. Moderation can begin once all required marks and absence reasons are validated.</p></div><CircularProgress label="marks submitted" value={67} valueLabel="67%" /></section><section className={styles.statGrid}><AcademicStat detail="2 currently active" icon={Exam} label="Examination cycles" tone="blue" value="4" /><AcademicStat detail="Across 10 grade levels" icon={FileText} label="Assessment components" tone="violet" value="138" /><AcademicStat detail="106 marks pending" icon={Student} label="Learners assessed" progress={92} tone="green" value="1,178" /><AcademicStat detail="Need controller review" icon={WarningCircle} label="Validation exceptions" tone="amber" value="14" /></section><div className={styles.layout}><WorkspacePanel action="View examination calendar" description="Current and recent cycles" title="Examinations"><div className={styles.tableWrap}><table aria-label="Examinations" className={styles.table}><thead><tr><th>Examination</th><th>Grades</th><th>Schedule</th><th>Progress</th><th>Status</th></tr></thead><tbody>{exams.map((row) => <tr key={row.name}><td><div className={styles.primaryCell}><strong>{row.name}</strong><span>{row.grades}</span></div></td><td>{row.grades}</td><td>{row.date}</td><td>{row.progress}</td><td><StatusPill tone={row.status === "Published" ? "success" : row.status === "Draft" ? "neutral" : row.status === "Moderation" ? "warning" : "info"}>{row.status}</StatusPill></td></tr>)}</tbody></table></div></WorkspacePanel><div className={styles.stack}><WorkspacePanel title="Publication readiness"><div className={styles.list}><div className={styles.listItem}><div className={`${styles.listIcon} ${styles.green}`}><CheckCircle size={17} /></div><div><strong>Exam structure validated</strong><span>48 subject components</span></div><StatusPill tone="success">Complete</StatusPill></div><div className={styles.listItem}><div className={`${styles.listIcon} ${styles.amber}`}><WarningCircle size={17} /></div><div><strong>Marks validation</strong><span>14 exceptions remaining</span></div><StatusPill tone="warning">In progress</StatusPill></div><div className={styles.listItem}><div className={`${styles.listIcon} ${styles.blue}`}><CalendarBlank size={17} /></div><div><strong>Publication window</strong><span>Opens 18 August</span></div><StatusPill tone="info">Scheduled</StatusPill></div></div></WorkspacePanel></div></div></div>; }
