"use client";

import { Bell, CalendarBlank, Check, CheckCircle, Clock, CurrencyDollar, Gear, IdentificationCard, WarningCircle } from "@phosphor-icons/react";
import { MoreActionsButton } from "@/components/ui/more-actions-button";
import { useState } from "react";
import styles from "./support.module.css";

const initialItems=[{id:1,title:"Attendance submission is overdue",detail:"Grade 7 · Section C has not submitted today’s attendance.",time:"8 minutes ago",group:"Today",type:"warning",icon:IdentificationCard,unread:true},{id:2,title:"Payment batch reconciled",detail:"46 of 48 transactions matched automatically. Two need review.",time:"24 minutes ago",group:"Today",type:"success",icon:CurrencyDollar,unread:true},{id:3,title:"Mid-term results readiness changed",detail:"Marks entry reached 67%. Four subjects are approaching deadline.",time:"1 hour ago",group:"Today",type:"info",icon:CheckCircle,unread:true},{id:4,title:"Academic calendar reminder",detail:"Primary Assessment 1 begins in five days.",time:"3 hours ago",group:"Today",type:"info",icon:CalendarBlank,unread:false},{id:5,title:"Teacher contract review due",detail:"Three contracts expire within 60 days.",time:"Yesterday · 4:15 PM",group:"Earlier",type:"warning",icon:Clock,unread:false}];
export function NotificationCenter(){const[items,setItems]=useState(initialItems);const markAll=()=>setItems(current=>current.map(item=>({...item,unread:false})));return <div className={styles.notificationPage}><header><div><span>Workspace</span><h1>Notifications</h1><p>Operational alerts, approvals, and background-job updates relevant to your current role and school.</p></div><div><button onClick={markAll} type="button"><Check size={15}/>Mark all as read</button><button type="button"><Gear size={15}/>Preferences</button></div></header><nav aria-label="Notification filters"><button className={styles.activeTab} type="button">All <span>{items.length}</span></button><button type="button">Unread <span>{items.filter(item=>item.unread).length}</span></button><button type="button">Approvals</button><button type="button">System</button></nav><div className={styles.notificationLayout}><main>{["Today","Earlier"].map(group=><section key={group}><h2>{group}</h2>{items.filter(item=>item.group===group).map(item=>{const Icon=item.icon;return <article className={item.unread?styles.unread:""} key={item.id}><div className={`${styles.notificationIcon} ${styles[item.type]}`}><Icon size={18}/></div><div><strong>{item.title}</strong><p>{item.detail}</p><time>{item.time}</time></div>{item.unread?<i aria-label="Unread"/>:null}<MoreActionsButton label={`Actions for ${item.title}`} /></article>})}</section>)}</main><aside><section className={styles.notificationSummary}><Bell size={21}/><h2>You’re up to date</h2><p>3 unread notifications. Critical alerts will also remain visible in their owning workspace.</p><dl><div><dt>Today</dt><dd>4</dd></div><div><dt>Approvals</dt><dd>2</dd></div><div><dt>System alerts</dt><dd>0</dd></div></dl></section><section className={styles.deliveryHealth}><CheckCircle size={18}/><div><strong>Delivery healthy</strong><span>Push and email channels operating normally.</span></div></section><section className={styles.safety}><WarningCircle size={18}/><div><strong>Notification safety</strong><span>Alerts never reveal protected student details on a locked device.</span></div></section></aside></div></div>}
