import { ArrowUpRight, CalendarBlank, CheckCircle, Clock, ShieldCheck, TrendUp, UsersThree, WarningCircle } from "@phosphor-icons/react/dist/ssr";
import styles from "./workspaces.module.css";

type VisualizationVariant = keyof typeof visualData | "calendar" | "settings" | "admin";

const visualData = {
  people: { title: "People growth", subtitle: "Active profiles · Last 6 months", values: [3180, 3212, 3258, 3310, 3374, 3448], labels: ["Feb", "Mar", "Apr", "May", "Jun", "Jul"], sideTitle: "Directory composition", segments: [{ label: "Students", value: 1284, percent: 37 }, { label: "Guardians", value: 1946, percent: 56 }, { label: "Employees", value: 218, percent: 7 }] },
  students: { title: "Enrollment trend", subtitle: "Academic-year enrollment · Last 6 terms", values: [1098, 1135, 1162, 1201, 1247, 1284], labels: ["T1 24", "T2 24", "T3 24", "T1 25", "T2 25", "T3 25"], sideTitle: "Students by level", segments: [{ label: "Primary", value: 498, percent: 39 }, { label: "Lower secondary", value: 452, percent: 35 }, { label: "Secondary", value: 334, percent: 26 }] },
  teachers: { title: "Teaching workload", subtitle: "Average weekly periods by department", values: [26, 24, 22, 25, 20, 23], labels: ["Math", "Science", "English", "Bangla", "ICT", "Social"], sideTitle: "Workload balance", segments: [{ label: "Within target", value: 72, percent: 84 }, { label: "Above target", value: 9, percent: 10 }, { label: "Below target", value: 5, percent: 6 }] },
  finance: { title: "Collections vs target", subtitle: "Monthly fee collection · ৳ lakh", values: [7.1, 7.8, 8.4, 8.1, 9.2, 8.42], labels: ["Feb", "Mar", "Apr", "May", "Jun", "Jul"], sideTitle: "Payment channels", segments: [{ label: "Online banking", value: 362000, percent: 43 }, { label: "Mobile wallet", value: 278000, percent: 33 }, { label: "Cash & card", value: 202000, percent: 24 }] },
  messages: { title: "Communication engagement", subtitle: "Delivery and read rate · Last 7 days", values: [68, 72, 74, 73, 78, 79, 81], labels: ["Wed", "Thu", "Sun", "Mon", "Tue", "Wed", "Thu"], sideTitle: "Channel performance", segments: [{ label: "In-app", value: 98, percent: 98 }, { label: "Email", value: 94, percent: 94 }, { label: "SMS", value: 97, percent: 97 }] },
  reports: { title: "Report usage trend", subtitle: "Views and exports · Last 6 months", values: [204, 238, 271, 296, 342, 386], labels: ["Feb", "Mar", "Apr", "May", "Jun", "Jul"], sideTitle: "Usage by domain", segments: [{ label: "Academics", value: 164, percent: 42 }, { label: "Finance", value: 112, percent: 29 }, { label: "People & workforce", value: 110, percent: 29 }] },
} as const;

function LineChart({ values, labels, title }: { values: readonly number[]; labels: readonly string[]; title: string }) {
  const max = Math.max(...values); const min = Math.min(...values); const range = max - min || 1;
  const points = values.map((value, index) => `${32 + index * (536 / (values.length - 1))},${145 - ((value - min) / range) * 105}`).join(" ");
  const area = `32,145 ${points} 568,145`;
  return <div className={styles.chartBox}><svg aria-label={`${title}: ${values.join(", ")}`} role="img" viewBox="0 0 600 175"><defs><linearGradient id={`fill-${title.replaceAll(" ", "-")}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="var(--workspace-accent)" stopOpacity=".24"/><stop offset="1" stopColor="var(--workspace-accent)" stopOpacity="0"/></linearGradient></defs>{[40,75,110,145].map((y) => <line className={styles.gridLine} key={y} x1="32" x2="568" y1={y} y2={y} />)}<polygon fill={`url(#fill-${title.replaceAll(" ", "-")})`} points={area} /><polyline className={styles.chartLine} points={points} />{values.map((value, index) => <g key={labels[index]}><circle className={styles.chartPoint} cx={32 + index * (536 / (values.length - 1))} cy={145 - ((value - min) / range) * 105} r="4" /><text className={styles.chartLabel} textAnchor="middle" x={32 + index * (536 / (values.length - 1))} y="166">{labels[index]}</text></g>)}</svg></div>;
}

function SegmentBreakdown({ title, segments }: { title: string; segments: ReadonlyArray<{ label: string; value: number; percent: number }> }) {
  return <div className={styles.breakdown}><div className={styles.breakdownTotal}><strong>{segments.reduce((sum, item) => sum + item.value, 0).toLocaleString()}</strong><span>{title.toLowerCase()}</span></div><div className={styles.segmentBar}>{segments.map((segment, index) => <i className={styles[`segment${index + 1}`]} key={segment.label} style={{ width: `${segment.percent}%` }} />)}</div><div className={styles.segmentList}>{segments.map((segment, index) => <div key={segment.label}><i className={styles[`segment${index + 1}`]} /><span>{segment.label}</span><strong>{segment.value.toLocaleString()}</strong><small>{segment.percent}%</small></div>)}</div></div>;
}

function StandardAnalytics({ variant }: { variant: keyof typeof visualData }) { const data = visualData[variant]; return <div className={styles.visualGrid}><section className={styles.analyticsCard}><header><div><h2>{data.title}</h2><p>{data.subtitle}</p></div><button type="button">Explore <ArrowUpRight size={13} /></button></header><LineChart labels={data.labels} title={data.title} values={data.values} /><footer><span><TrendUp size={13} /> Trending upward</span><small>Updated 18 minutes ago</small></footer></section><section className={styles.analyticsCard}><header><div><h2>{data.sideTitle}</h2><p>Current verified records</p></div></header><SegmentBreakdown segments={data.segments} title={data.sideTitle} /></section></div>; }

function CalendarVisual() { const days = Array.from({ length: 35 }, (_, i) => i - 2); const events = new Map([[21,"today"],[26,"exam"],[28,"meeting"],[31,"deadline"]]); return <div className={styles.visualGrid}><section className={styles.analyticsCard}><header><div><h2>July 2026</h2><p>School-wide calendar · Asia/Dhaka</p></div><button type="button">Month view <CalendarBlank size={13} /></button></header><div className={styles.monthGrid}>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((day) => <strong key={day}>{day}</strong>)}{days.map((day,index) => <div className={`${day < 1 || day > 31 ? styles.outsideDay : ""} ${events.has(day) ? styles[events.get(day)!] : ""}`} key={index}>{day > 0 && day <= 31 ? <span>{day}</span> : null}{events.has(day) ? <i /> : null}</div>)}</div><div className={styles.calendarLegend}><span><i className={styles.exam} />Assessment</span><span><i className={styles.meeting} />Meeting</span><span><i className={styles.deadline} />Deadline</span></div></section><section className={styles.analyticsCard}><header><div><h2>Next seven days</h2><p>4 scheduled items</p></div></header><div className={styles.eventTimeline}>{[["21 Jul","Marks deadline","Exam office"],["23 Jul","Faculty meeting","All teaching staff"],["26 Jul","Primary Assessment 1","Grades 1–5"],["28 Jul","Parent-teacher meeting","Families & teachers"]].map(([date,title,detail]) => <article key={title}><time>{date}</time><i /><div><strong>{title}</strong><span>{detail}</span></div></article>)}</div></section></div>; }

function ReportsVisual() { return <><StandardAnalytics variant="reports" /><div className={styles.reportStrip}><article><div><CheckCircle size={18} /></div><span>Data quality</span><strong>99.8%</strong><small>12 automated checks passed</small></article><article><div><Clock size={18} /></div><span>Median generation</span><strong>4.2s</strong><small>Within the 8-second budget</small></article><article><div><UsersThree size={18} /></div><span>Active report users</span><strong>68</strong><small>Across 11 role groups</small></article><article><div><ArrowUpRight size={18} /></div><span>Exports this month</span><strong>126</strong><small>All access-audited</small></article></div></>; }

function ConfigurationVisual({ admin = false }: { admin?: boolean }) { const rows = admin ? [["Identity & access",100],["Integration health",89],["Audit coverage",100],["Backup & recovery",96]] as const : [["School profile",100],["Academic defaults",100],["Locale & terminology",92],["Communication policy",96],["Emergency readiness",78]] as const; return <div className={styles.visualGrid}><section className={styles.analyticsCard}><header><div><h2>{admin ? "Control effectiveness" : "Configuration coverage"}</h2><p>Effective and validated settings</p></div><button type="button">Review details</button></header><div className={styles.coverageList}>{rows.map(([label,value]) => <div key={label}><span>{label}</span><div><i style={{ width: `${value}%` }} /></div><strong>{value}%</strong></div>)}</div></section><section className={styles.analyticsCard}><header><div><h2>{admin ? "Platform signals" : "Change governance"}</h2><p>Past 30 days</p></div></header><div className={styles.healthGrid}>{admin ? <><article><ShieldCheck size={19} /><strong>0</strong><span>Security findings</span></article><article><CheckCircle size={19} /><strong>99.98%</strong><span>Service availability</span></article><article><WarningCircle size={19} /><strong>1</strong><span>Integration alert</span></article><article><UsersThree size={19} /><strong>214</strong><span>Active users</span></article></> : <><article><CheckCircle size={19} /><strong>28</strong><span>Active overrides</span></article><article><Clock size={19} /><strong>4</strong><span>Pending changes</span></article><article><ShieldCheck size={19} /><strong>2</strong><span>Need approval</span></article><article><WarningCircle size={19} /><strong>1</strong><span>Recommendation</span></article></>}</div></section></div>; }

export function WorkspaceVisualizations({ variant }: { variant: VisualizationVariant }) {
  if (variant === "calendar") return <CalendarVisual />;
  if (variant === "reports") return <ReportsVisual />;
  if (variant === "settings") return <ConfigurationVisual />;
  if (variant === "admin") return <ConfigurationVisual admin />;
  return <StandardAnalytics variant={variant} />;
}
