import { CalendarCheck, CheckCircle, Clock, Student, TrendUp, WarningCircle } from "@phosphor-icons/react/dist/ssr";
import type { Metadata } from "next";
import { CircularProgress } from "@/components/ui/circular-progress";
import { AcademicPageHeader, AcademicStat, StatusPill, WorkspacePanel } from "@/features/academics/academic-ui";
import styles from "@/features/academics/academics.module.css";

export const metadata: Metadata = { title: "Attendance" };
const sections = [{ section: "Grade 10 · A", teacher: "Farhana Akter", present: "38 / 40", rate: "95.0%", status: "Submitted" }, { section: "Grade 9 · B", teacher: "Rashid Hasan", present: "37 / 39", rate: "94.9%", status: "Submitted" }, { section: "Grade 8 · A", teacher: "Nadia Rahman", present: "39 / 41", rate: "95.1%", status: "Submitted" }, { section: "Grade 7 · C", teacher: "Mahmud Karim", present: "—", rate: "—", status: "Pending" }, { section: "Grade 6 · B", teacher: "Samira Chowdhury", present: "35 / 38", rate: "92.1%", status: "Review" }];
export default function AttendancePage() { return <div className={styles.page}><AcademicPageHeader action="Take attendance" description="Monitor daily capture, resolve exceptions, and protect complete attendance records." title="Attendance" /><section className={styles.hero}><div className={styles.heroCopy}><span>Today · 22 July</span><h2>Attendance is above the school target.</h2><p>42 of 48 sections have submitted attendance. Six classes remain, with the next deadline at 11:30 AM.</p></div><CircularProgress label="school attendance" value={94.6} valueLabel="94.6%" /></section><section className={styles.statGrid}><AcademicStat detail="Of 1,284 enrolled" icon={CheckCircle} label="Present today" tone="green" value="1,215" /><AcademicStat detail="3.7% of enrollment" icon={Student} label="Absent" tone="amber" value="48" /><AcademicStat detail="1.6% arrived late" icon={Clock} label="Late arrivals" tone="violet" value="21" /><AcademicStat detail="6 sections remaining" icon={CalendarCheck} label="Submission progress" progress={88} tone="blue" value="42 / 48" /></section><div className={styles.layout}><WorkspacePanel action="View all sections" description="Live submission status" title="Today’s class attendance"><div className={styles.tableWrap}><table aria-label="Today’s class attendance" className={styles.table}><thead><tr><th>Section</th><th>Class teacher</th><th>Present</th><th>Rate</th><th>Status</th></tr></thead><tbody>{sections.map((row) => <tr key={row.section}><td><strong>{row.section}</strong></td><td>{row.teacher}</td><td>{row.present}</td><td>{row.rate}</td><td><StatusPill tone={row.status === "Submitted" ? "success" : row.status === "Pending" ? "warning" : "danger"}>{row.status}</StatusPill></td></tr>)}</tbody></table></div></WorkspacePanel><div className={styles.stack}><WorkspacePanel action="Resolve all" title="Needs attention"><div className={styles.alertList}><div className={styles.alertItem}><WarningCircle size={17} /><div><strong>6 sections haven’t submitted</strong><span>Next reminder in 18 minutes</span></div></div><div className={styles.alertItem}><WarningCircle size={17} /><div><strong>12 student exceptions</strong><span>Missing reasons or relationship notes</span></div></div></div></WorkspacePanel><WorkspacePanel title="7-day trend"><div className={styles.list}><div className={styles.listItem}><div className={`${styles.listIcon} ${styles.green}`}><TrendUp size={17} /></div><div><strong>+1.8% improvement</strong><span>Compared with the previous week</span></div><StatusPill tone="success">On target</StatusPill></div></div></WorkspacePanel></div></div></div>; }
