"use client";
import { useState } from "react";
import { ArrowDown, Bank, CheckCircle, Clock, CurrencyDollar, MagnifyingGlass, Plus, Receipt, WarningCircle } from "@phosphor-icons/react";
import { WorkspaceVisualizations } from "@/features/workspaces/workspace-visualizations";
import styles from "./finance.module.css";
type Tab="Overview"|"Student accounts"|"Collection desk"|"Billing runs"|"Arrears"|"Waivers & refunds";
type Row=[string,string,string,string,string,string,string];
const tabs:Tab[]=["Overview","Student accounts","Collection desk","Billing runs","Arrears","Waivers & refunds"];
const data:Record<Exclude<Tab,"Overview">,{lead:string;value:string;detail:string;cards:[string,string,string][];title:string;headers:string[];rows:Row[];queue:[string,string,string][]}>={
"Student accounts":{lead:"Total billed · July",value:"৳11,70,000",detail:"Across 1,284 active accounts",cards:[["Accounts clear","956","74.5% of accounts"],["Balance due","284","Within due date"],["Overdue accounts","44","Requires follow-up"]],title:"Student account ledger",headers:["Billed","Paid","Balance"],rows:[["STU-2026-0142","Ayesha Rahman","Grade 8 · A","৳32,800","৳32,800","৳0","Paid"],["STU-2026-0158","Rafi Islam","Grade 9 · B","৳41,500","৳36,500","৳5,000","Due"],["STU-2026-0189","Nafisa Akter","Grade 6 · B","৳28,400","৳18,400","৳10,000","Overdue"],["STU-2026-0201","Saad Hasan","Grade 10 · C","৳46,000","৳46,000","৳0","Paid"]],queue:[["Account exceptions","12 accounts","Review"],["Unapplied credits","৳7,300","Allocate"],["Disputed charges","4 accounts","Resolve"]]},
"Collection desk":{lead:"Collected today",value:"৳1,18,700",detail:"48 successful receipts",cards:[["Receipts issued","48","Last at 10:42 AM"],["Awaiting provider","7","৳18,500 pending"],["Cash drawer","৳31,200","Matches expected"]],title:"Collection transactions",headers:["Amount","Method","Received"],rows:[["TXN-88421","Nafisa Akter","STU-2026-0189","৳6,500","Mobile wallet","10:38 AM","Confirm"],["RCT-24071","Rafi Islam","STU-2026-0158","৳12,500","Online banking","10:22 AM","Receipted"],["CSH-01882","Saad Hasan","STU-2026-0201","৳15,000","Cash","9:54 AM","Reconcile"],["TXN-88409","Maya Chowdhury","STU-2026-0208","৳8,200","Card","9:31 AM","Failed"]],queue:[["Provider confirmations","7 transactions","Match"],["Cash reconciliation","3 entries","Review"],["Failed payments","2 attempts","Follow up"]]},
"Billing runs":{lead:"July billing",value:"৳11,70,000",detail:"1,284 accounts charged",cards:[["Posted charges","1,284","No failures"],["Scheduled runs","2","Next: 1 August"],["Draft charges","9","৳13,500 in review"]],title:"Billing run history",headers:["Accounts","Run value","Run date"],rows:[["BILL-2026-07","July tuition","All active students","1,284","৳11,70,000","1 Jul 2026","Posted"],["BILL-2026-T2","Term 2 activity fee","Grades 6–10","728","৳3,64,000","20 Jul 2026","Review"],["BILL-TRN-08","August transport","Subscribers","312","৳2,49,600","1 Aug 2026","Scheduled"],["BILL-LIB-02","Library replacement","Selected accounts","9","৳13,500","Draft","Draft"]],queue:[["Term 2 activity fee","Ready to approve","Review"],["August transport","Scheduled 1 Aug","View"],["Draft exceptions","9 accounts","Resolve"]]},
"Arrears":{lead:"Outstanding receivables",value:"৳3,28,000",detail:"Across 328 student accounts",cards:[["Overdue accounts","44","3.4% of accounts"],["Payment plans","18","৳86,000 scheduled"],["60+ days overdue","৳21,000","6 accounts"]],title:"Arrears worklist",headers:["Outstanding","Age","Guardian"],rows:[["STU-2026-0189","Nafisa Akter","Grade 6 · B","৳10,000","47 days","Kamal Akter","Promise due"],["STU-2026-0134","Tanvir Ahmed","Grade 9 · A","৳8,500","32 days","Rehana Ahmed","Contacted"],["STU-2026-0208","Maya Chowdhury","Grade 7 · A","৳6,200","18 days","Amin Chowdhury","Reminder sent"],["STU-2026-0071","Abrar Hasan","Grade 10 · B","৳14,000","68 days","Salma Hasan","Payment plan"]],queue:[["Promises overdue","2 families","Contact"],["Follow-ups today","9 families","Open"],["Plan reviews due","3 accounts","Review"]]},
"Waivers & refunds":{lead:"Adjustments this month",value:"৳42,700",detail:"Waivers, credits, and refunds",cards:[["Approved","৳31,200","18 requests"],["Awaiting approval","৳8,500","4 requests"],["Refunds payable","৳3,000","1 payout"]],title:"Waivers and refunds",headers:["Type","Amount","Reason"],rows:[["WVR-00618","Nafisa Akter","STU-2026-0189","Waiver","৳4,000","Need-based scholarship","Approval"],["RFD-00241","Maya Chowdhury","STU-2026-0208","Refund","৳2,500","Transport cancelled","Finance review"],["WVR-00611","Rafi Islam","STU-2026-0158","Waiver","৳1,200","Sibling discount","Applied"],["RFD-00236","Saad Hasan","STU-2026-0201","Refund","৳3,000","Duplicate payment","Paid"]],queue:[["Awaiting approval","4 requests","Review"],["Evidence missing","2 requests","Action"],["Approved payout","৳3,000","Process"]]}};
const recent:Row[]=[["RCT-24071","Rafi Islam","STU-2026-0158","৳12,500","Tuition · July","Online banking","Reconciled"],["RCT-24070","Ayesha Rahman","STU-2026-0142","৳8,200","Tuition · July","Card","Allocated"],["PAY-44218","Nafisa Akter","STU-2026-0189","৳6,500","Awaiting confirmation","Mobile wallet","Pending"],["RCT-24069","Saad Hasan","STU-2026-0201","৳15,000","Tuition + transport","Cash","Reconciled"]];
function Summary({lead,value,detail,cards}:{lead:string;value:string;detail:string;cards:[string,string,string][]}){return <section className={styles.balance}><div><span>{lead}</span><strong>{value}</strong><small>{detail}</small><div><i/></div></div>{cards.map(([l,v,d],i)=><article key={l}>{i===0?<CheckCircle size={17}/>:i===1?<Clock size={17}/>:<WarningCircle size={17}/>}<span>{l}</span><strong>{v}</strong><small>{d}</small></article>)}</section>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:Row[]}){return <section className={styles.panel}><header><div><h2>{title}</h2><p>Current status and operational detail</p></div><div><label><MagnifyingGlass size={14}/><input aria-label={`Search ${title}`} placeholder="Name, ID…"/></label><button type="button"><ArrowDown size={13}/> Export</button></div></header><div className={styles.tableWrap}><table aria-label={title}><thead><tr><th>Reference</th><th>Account / record</th>{headers.map(h=><th key={h}>{h}</th>)}<th>State</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td><div><strong>{r[1]}</strong><span>{r[2]}</span></div></td><td><b>{r[3]}</b></td><td>{r[4]}</td><td>{r[5]}</td><td><span className={r[6]==="Paid"||r[6]==="Posted"||r[6]==="Receipted"||r[6]==="Reconciled"||r[6]==="Allocated"||r[6]==="Applied"||r[6]==="Payment plan"?styles.success:styles.pending}>{r[6]}</span></td></tr>)}</tbody></table></div></section>}
function Aging(){return <section className={styles.panel}><header><div><h2>Receivables aging</h2><p>৳3,28,000 outstanding</p></div></header><div className={styles.aging}>{[["Current",184000,56],["1–30 days",82000,25],["31–60 days",41000,13],["60+ days",21000,6]].map(([l,v,p])=><div key={l}><span>{l}</span><strong>৳{Number(v).toLocaleString()}</strong><div><i style={{width:`${p}%`}}/></div><small>{p}%</small></div>)}</div></section>}
function Queue({items}:{items:[string,string,string][]}){return <section className={styles.panel}><header><div><h2>Action queue</h2><p>Items requiring attention</p></div></header><div className={styles.aging}>{items.map(([l,d,a])=><div key={l}><span>{l}</span><strong>{a}</strong><div><i style={{width:"72%"}}/></div><small>{d}</small></div>)}</div></section>}
function Overview(){return <><Summary lead="Collected in July" value="৳8,42,000" detail="72% of ৳11,70,000 target" cards={[["Allocated","৳8,16,200","96.9% confirmed"],["Pending confirmation","৳18,500","7 transactions"],["Unallocated","৳7,300","Cashier review"]]}/><WorkspaceVisualizations variant="finance"/><div className={styles.financeGrid}><Table title="Recent payments" headers={["Amount","Allocation","Method"]} rows={recent}/><aside><Aging/><section className={`${styles.panel} ${styles.reconcile}`}><Bank size={20}/><div><h2>Daily reconciliation</h2><p>14 transactions await provider or cashier matching.</p><button type="button">Open reconciliation desk</button></div></section><section className={`${styles.panel} ${styles.receipt}`}><Receipt size={18}/><div><strong>48 receipts issued today</strong><span>Last receipt RCT-24071 · 10:42 AM</span></div></section></aside></div></>}
export function FinanceWorkspace(){const[active,setActive]=useState<Tab>("Overview");const c=active==="Overview"?null:data[active];return <div className={styles.page}><header><div><span>Finance / Fees & collection</span><h1>Fee management</h1><p>Bill accurately, collect flexibly, allocate every payment, and close each cycle with reconciliation evidence.</p></div><div><button className={styles.secondary} type="button"><Plus size={15}/> Generate charges</button><button type="button"><CurrencyDollar size={15}/> Collect payment</button></div></header><nav aria-label="Finance sections" className={styles.tabs} role="tablist">{tabs.map(t=><button aria-selected={active===t} className={active===t?styles.active:""} key={t} onClick={()=>setActive(t)} role="tab" type="button">{t}</button>)}</nav><section aria-live="polite" role="tabpanel">{c?<><Summary lead={c.lead} value={c.value} detail={c.detail} cards={c.cards}/><div className={styles.financeGrid}><Table title={c.title} headers={c.headers} rows={c.rows}/><aside><Queue items={c.queue}/><Aging/></aside></div></>:<Overview/>}</section></div>}
