import { Buildings, CalendarBlank, ChalkboardTeacher, Clock, WarningCircle } from "@phosphor-icons/react/dist/ssr";
import type { Metadata } from "next";
import { AcademicPageHeader, AcademicStat, WorkspacePanel } from "@/features/academics/academic-ui";
import styles from "@/features/academics/academics.module.css";

export const metadata: Metadata = { title: "Timetable" };
const days = ["Time", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"];
const slots = [{ time: "08:00", lessons: ["Math · 10A", "English · 9B", "Physics · 10A", "Bangla · 8C", "Math · 9A"] }, { time: "09:00", lessons: ["Physics · 9B", "Math · 10A", "English · 8C", "Science · 7A", "ICT · 10B"] }, { time: "10:15", lessons: ["English · 8A", "Chemistry · 10B", "Math · 9A", "Physics · 9B", "Bangla · 7C"] }, { time: "11:15", lessons: ["ICT · 10A", "Bangla · 8B", "Biology · 9A", "Math · 7C", "English · 10B"] }];
export default function TimetablePage() { return <div className={styles.page}><AcademicPageHeader action="Create timetable" description="Coordinate classes, teachers, rooms, periods, and substitution coverage." title="Timetable" /><section className={styles.statGrid}><AcademicStat detail="Across 38 active sections" icon={CalendarBlank} label="Scheduled periods" tone="blue" value="1,146" /><AcademicStat detail="98.7% allocation coverage" icon={ChalkboardTeacher} label="Teacher assignments" progress={99} tone="green" value="84 / 86" /><AcademicStat detail="4 specialist labs" icon={Buildings} label="Rooms in use" tone="violet" value="46" /><AcademicStat detail="Requires review" icon={WarningCircle} label="Open conflicts" tone="amber" value="3" /></section><div className={styles.layout}><WorkspacePanel action="Open full planner" description="Current week · All sections" title="Weekly timetable"><div className={styles.tableWrap}><div className={styles.weekGrid}>{days.map((day) => <div className={styles.weekHeader} key={day}>{day}</div>)}{slots.flatMap((slot) => [<div className={styles.timeCell} key={`${slot.time}-time`}>{slot.time}</div>, ...slot.lessons.map((lesson, index) => <div className={styles.lesson} key={`${slot.time}-${index}`}><strong>{lesson.split(" · ")[0]}</strong><span>{lesson.split(" · ")[1]} · Room {101 + index}</span></div>)])}</div></div></WorkspacePanel><div className={styles.stack}><WorkspacePanel title="Today’s next periods"><div className={styles.schedule}>{[{ time: "10:15", name: "English · Grade 8A", room: "Room 104" }, { time: "11:15", name: "Faculty coordination", room: "Meeting room" }, { time: "12:30", name: "Mathematics · Grade 10A", room: "Room 201" }].map((item) => <div className={styles.scheduleRow} key={item.time}><time>{item.time}</time><i /><div><strong>{item.name}</strong><span>{item.room}</span></div><small>Upcoming</small></div>)}</div></WorkspacePanel><WorkspacePanel action="Resolve" title="Scheduling conflicts"><div className={styles.alertList}><div className={styles.alertItem}><WarningCircle size={17} /><div><strong>Room 204 double-booked</strong><span>Thursday · Period 4</span></div></div><div className={styles.alertItem}><Clock size={17} /><div><strong>Teacher availability conflict</strong><span>2 assignments need reassignment</span></div></div></div></WorkspacePanel></div></div></div>; }
